<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  
  <!-- Global packages (private, build-time packages for all projects) -->
  <ItemGroup>
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.10.85" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <GlobalPackageReference Include="Umbraco.GitVersioning.Extensions" Version="0.2.0" />
  </ItemGroup>
  
  <!-- Umbraco packages -->
  <PropertyGroup>
    <UmbracoCmsPackageVersion>[18.0.0-rc3, 19)</UmbracoCmsPackageVersion>
    <UmbracoDeployPackageVersion>[18.0.0-rc3, 19)</UmbracoDeployPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Umbraco.Cms.Web.Common" Version="$(UmbracoCmsPackageVersion)" />
    <PackageVersion Include="Umbraco.Deploy.Infrastructure" Version="$(UmbracoDeployPackageVersion)" />
  </ItemGroup>
</Project>
