<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- Enable multi-level merging -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />
  
  <!-- Microsoft packages -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
  </ItemGroup>

  <!-- Umbraco packages -->
  <ItemGroup>
    <PackageVersion Include="Umbraco.Cms.Tests" Version="17.0.0-rc4" />
  </ItemGroup>

  <!-- Third-party packages -->
  <ItemGroup>
    <PackageVersion Include="Moq" Version="4.17.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.2.0" />
  </ItemGroup>
</Project>
