<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- Enable multi-level merging -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />
  <!-- Microsoft packages -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.2.3" />
  </ItemGroup>
  <!-- Test packages -->
  <ItemGroup>
    <PackageVersion Include="NUnit" Version="4.6.1" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>
  <!-- Umbraco packages -->
  <ItemGroup>
    <PackageVersion Include="Umbraco.Cms.Tests" Version="18.0.0" />
  </ItemGroup>
</Project>
